security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

ribbon:
  IsSecure: false

spring:
  cloud:
    services:
      registrationMethod: route

